#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/luo?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
#  data:
#    mongodb:
#      authentication-database: admin
#      auto-index-creation: true
#      connections-per-host: 20
#      database: luo
#      max-wait-time: 120000
#      threads-allowed-to-block-for-connection-multiplier: 5
#      uri: mongodb://localhost:27017/luo
#  redis:
#    password: 123456
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 2
#        max-wait: -1
#  thymeleaf:
#    cache: false
## 配置MyBatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#okta:
#  oauth2:
#    baseUri: https://dev-93007508.okta.com
#    getCodeUri: /oauth2/v1/authorize
#    getTokenUri: /oauth2/v1/token
#    getUserUri: /oauth2/v1/userinfo
#    issuer: https://dev-93007508.okta.com/oauth2/default
#    client-id: 0oa8xgeqr2QdZ5iWu5d7
#    client-secret: MUwHsCjjI6fdNnwd1ddMQHzPuV2HzpBCQJRhzKbn
#
