spring:
  datasource:
    url: jdbc:mysql://192.2.2.167:3306/auth
    username: root
    password: rgJ4q,q_k#rk
  data:
    redis:
      host: 192.2.2.183
      port: 6379
      password: 123456
      database: 1