spring:
  datasource:
    url: jdbc:mysql://192.168.81.204:3306/school_info_luo
    username: root
    password: XYXX@07_27
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
  data:
    redis:
      host: 192.168.81.205
      port: 36379
      password: XYXX@07_27
      connection-minimum-idle-size: 8
      connection-pool-size: 8