server:
  port: 519
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://192.168.81.204:3306/school_info_luo
    username: root
    password: XYXX@07_27
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      jdbc-url: 192.168.81.204:3306/school_info_luo
