CREATE TABLE `user` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `username` varchar(255) DEFAULT NULL,
                        `account` varchar(255) DEFAULT NULL,
                        `password` varchar(255) DEFAULT NULL,
                        `avatar` varchar(255) DEFAULT NULL,
                        `email` varchar(255) DEFAULT NULL,
                        `phone` varchar(255) DEFAULT NULL,
                        `tenant_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
                        `create_user` varchar(255) DEFAULT NULL,
                        `update_user` varchar(255) DEFAULT NULL,
                        `create_time` datetime DEFAULT NULL,
                        `update_time` datetime DEFAULT NULL,
                        `deleted` tinyint DEFAULT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `account` (`account`),
                        KEY `idx_tenantId` (`tenant_id`),
                        KEY `idx_account` (`account`),
                        KEY `idx_deleted` (`deleted`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;