#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      auto-index-creation: true
#      connections-per-host: 20
#      database: luo
#      max-wait-time: 120000
#      threads-allowed-to-block-for-connection-multiplier: 5
#      uri: mongodb://localhost:27017/luo
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 123456
#    url: jdbc:mysql://localhost:3307/luo?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#  redis:
#    host: localhost
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 2
#    password: 123456
#    port: 6379