name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install
        env:
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: luo
          path: build/libs/*.jar